name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '12 */1 * * *'
    # “At minute 10 past every hour.”

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2

    - name: install deps
      run: |
        npm ci
        npx playwright install

    - name: Fetch latest data
      env:
        FIRST_EMAIL:    ${{ secrets.FIRST_EMAIL }}
        FIRST_PASSWORD: ${{ secrets.FIRST_PASSWORD }}
        SHEET_ID:       ${{ secrets.SHEET_ID }}
        SHEETS_EMAIL:   ${{ secrets.SHEETS_EMAIL }}
        SHEETS_KEY:     ${{ secrets.SHEETS_KEY }}
      run: xvfb-run npm run start
